version: '3.3'

services: 
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always 
    env_file:
      - .\Progamas\CompassUol\Sprint_3\Exercicios\docker_desenvolvedores\composer\2_variaveis\config\db.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .\Progamas\CompassUol\Sprint_3\Exercicios\docker_desenvolvedores\composer\2_variaveis\config\wp.env


volumes:
  db_data: {}
